
# Vector Store Configuration
# Auto-generated by load_vector_store.ipynb

VECTOR_STORE_PATH = "d:\10 acadamy\Intelligent Complaint Analysis for Financial Services\notebooks\vector_store"
COLLECTION_NAME = "financial_complaints"
TOTAL_DOCUMENTS = 10000
DATA_SOURCE = "data/processed/complaint_metadata_full.parquet"
LOAD_DATE = "2026-01-12 12:52:10"

# Usage in main notebook:
# from src.config import VECTOR_STORE_PATH, COLLECTION_NAME
# import chromadb
# client = chromadb.PersistentClient(path=VECTOR_STORE_PATH)
# collection = client.get_collection(COLLECTION_NAME)
